trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    enableAutomaticCodeQLInstall: true
    languages: 'csharp'
    querysuite: 'code-scanning'
    buildtype: 'manual'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: |
    echo "Listing files..."
    ls -R
  displayName: 'Show folder structure'

- task: AdvancedSecurity-Codeql-Analyze@1
  displayName: Perform CodeQL Analysis
  continueOnError: true
  condition: always()

- task: Docker@2
  inputs:
    containerRegistry: 'NewPractice'
    repository: 'ambarajv/PracticeDotNetSelf'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/PracticeDotNetSelf/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/PracticeDotNetSelf'